spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        defer-datasource-initialization: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/karina #?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ahqhRk123@
    driver-class-name: com.mysql.cj.jdbc.Driver
